// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UExpo.Repository.Context;

#nullable disable

namespace UExpo.Repository.Migrations
{
    [DbContext(typeof(UExpoDbContext))]
    [Migration("20240801230550_initial-create")]
    partial class initialcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("UExpo.Repository.Dao.CallCenterChatDao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AttendentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("AttendentLang")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UserLang")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id")
                        .HasName("call_center_pkey");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("call_center_chat", (string)null);
                });

            modelBuilder.Entity("UExpo.Repository.Dao.CallCenterMessageDao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Readed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ReceiverLang")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SendedMessage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SenderLang")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TranslatedMessage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id")
                        .HasName("call_center_message_pkey");

                    b.HasIndex("ChatId");

                    b.ToTable("call_center_message", (string)null);
                });

            modelBuilder.Entity("UExpo.Repository.Dao.UserDao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Enterprise")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsEmailValidated")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id")
                        .HasName("user_pkey");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("UExpo.Repository.Dao.CallCenterChatDao", b =>
                {
                    b.HasOne("UExpo.Repository.Dao.UserDao", "User")
                        .WithOne("CallCenterChat")
                        .HasForeignKey("UExpo.Repository.Dao.CallCenterChatDao", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UExpo.Repository.Dao.CallCenterMessageDao", b =>
                {
                    b.HasOne("UExpo.Repository.Dao.CallCenterChatDao", "CallCenterChat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CallCenterChat");
                });

            modelBuilder.Entity("UExpo.Repository.Dao.CallCenterChatDao", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("UExpo.Repository.Dao.UserDao", b =>
                {
                    b.Navigation("CallCenterChat")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
