// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UExpo.Repository.Context;

#nullable disable

namespace UExpo.Repository.Migrations
{
    [DbContext(typeof(UExpoDbContext))]
    [Migration("20240801121846_add-chat-tables")]
    partial class addchattables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("UExpo.Repository.Dao.CallCenterChatDao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AttendentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("AttendentLang")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserDaoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UserLang")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UserDaoId")
                        .IsUnique();

                    b.ToTable("CallCenterChatDao");
                });

            modelBuilder.Entity("UExpo.Repository.Dao.CallCenterMessageDao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CallCenterChatDaoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Readed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ReceiverLang")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SendedMessage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SenderLang")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TranslatedMessage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CallCenterChatDaoId");

                    b.ToTable("CallCenterMessageDao");
                });

            modelBuilder.Entity("UExpo.Repository.Dao.UserDao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Enterprise")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsEmailValidated")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UExpo.Repository.Dao.CallCenterChatDao", b =>
                {
                    b.HasOne("UExpo.Repository.Dao.UserDao", "UserDao")
                        .WithOne("CallCenterChatDao")
                        .HasForeignKey("UExpo.Repository.Dao.CallCenterChatDao", "UserDaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserDao");
                });

            modelBuilder.Entity("UExpo.Repository.Dao.CallCenterMessageDao", b =>
                {
                    b.HasOne("UExpo.Repository.Dao.CallCenterChatDao", "CallCenterChatDao")
                        .WithMany("Messages")
                        .HasForeignKey("CallCenterChatDaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CallCenterChatDao");
                });

            modelBuilder.Entity("UExpo.Repository.Dao.CallCenterChatDao", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("UExpo.Repository.Dao.UserDao", b =>
                {
                    b.Navigation("CallCenterChatDao")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
