// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UExpo.Repository.Context;

#nullable disable

namespace UExpo.Repository.Migrations
{
    [DbContext(typeof(UExpoDbContext))]
    [Migration("20240821224049_add-place-table")]
    partial class addplacetable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("UExpo.Domain.Dao.AdminDao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id")
                        .HasName("admin_pkey");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("admin", (string)null);
                });

            modelBuilder.Entity("UExpo.Domain.Dao.CallCenterChatDao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AdminId")
                        .HasColumnType("char(36)");

                    b.Property<string>("AdminLang")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UserLang")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id")
                        .HasName("call_center_pkey");

                    b.HasIndex("AdminId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("call_center_chat", (string)null);
                });

            modelBuilder.Entity("UExpo.Domain.Dao.CallCenterMessageDao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Readed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ReceiverLang")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SendedMessage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SenderLang")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TranslatedMessage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id")
                        .HasName("call_center_message_pkey");

                    b.HasIndex("ChatId");

                    b.ToTable("call_center_message", (string)null);
                });

            modelBuilder.Entity("UExpo.Domain.Dao.CatalogDao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("JsonTable")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id")
                        .HasName("catalog_pkey");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("catalog", (string)null);
                });

            modelBuilder.Entity("UExpo.Domain.Dao.CatalogItemImageDao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CatalogId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id")
                        .HasName("catalog_item_image_pkey");

                    b.HasIndex("CatalogId");

                    b.ToTable("catalog_item_image", (string)null);
                });

            modelBuilder.Entity("UExpo.Domain.Dao.CatalogPdfDao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CatalogId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id")
                        .HasName("catalog_pdf_pkey");

                    b.HasIndex("CatalogId");

                    b.ToTable("catalog_pdf", (string)null);
                });

            modelBuilder.Entity("UExpo.Domain.Dao.PlaceDao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("place_pkey");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("place", (string)null);
                });

            modelBuilder.Entity("UExpo.Domain.Dao.UserDao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Enterprise")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsEmailValidated")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id")
                        .HasName("user_pkey");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("UExpo.Domain.Dao.CallCenterChatDao", b =>
                {
                    b.HasOne("UExpo.Domain.Dao.AdminDao", "Admin")
                        .WithMany("CallCenterChats")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("UExpo.Domain.Dao.UserDao", "User")
                        .WithOne("CallCenterChat")
                        .HasForeignKey("UExpo.Domain.Dao.CallCenterChatDao", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UExpo.Domain.Dao.CallCenterMessageDao", b =>
                {
                    b.HasOne("UExpo.Domain.Dao.CallCenterChatDao", "CallCenterChat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CallCenterChat");
                });

            modelBuilder.Entity("UExpo.Domain.Dao.CatalogDao", b =>
                {
                    b.HasOne("UExpo.Domain.Dao.UserDao", "User")
                        .WithOne("Catalog")
                        .HasForeignKey("UExpo.Domain.Dao.CatalogDao", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UExpo.Domain.Dao.CatalogItemImageDao", b =>
                {
                    b.HasOne("UExpo.Domain.Dao.CatalogDao", "Catalog")
                        .WithMany("ItemImages")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("UExpo.Domain.Dao.CatalogPdfDao", b =>
                {
                    b.HasOne("UExpo.Domain.Dao.CatalogDao", "Catalog")
                        .WithMany("Pdfs")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("UExpo.Domain.Dao.AdminDao", b =>
                {
                    b.Navigation("CallCenterChats");
                });

            modelBuilder.Entity("UExpo.Domain.Dao.CallCenterChatDao", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("UExpo.Domain.Dao.CatalogDao", b =>
                {
                    b.Navigation("ItemImages");

                    b.Navigation("Pdfs");
                });

            modelBuilder.Entity("UExpo.Domain.Dao.UserDao", b =>
                {
                    b.Navigation("CallCenterChat");

                    b.Navigation("Catalog");
                });
#pragma warning restore 612, 618
        }
    }
}
